[package]
name = "varre-assets"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
include_bytes_aligned = "0.2.0"

[build-dependencies]
regex = "1.12.2"
include_bytes_aligned = "0.2.0"
