[package]
name = "varre-assets"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
include_bytes_aligned = "0.2.0"
glam = "0.30.9"

[build-dependencies]
regex = "1.12.2"
include_bytes_aligned = "0.2.0"
russimp = { version = "3.2.1" , features = ["prebuilt"]}
glam = "0.30.9"
